/* Too Hot Threshold */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-01'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/* Too Cold Threshold */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-02'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/* Zone temperature too high */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20-req-measures-a', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-20'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20-req-measures-b', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-20'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempCoolingSp','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/* Zone temperature too low */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21-req-measures-a', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-21'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21-req-measures-b', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-21'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempHeatingSp','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/* Cooling does not work */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09-req-measures-a', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-09'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09-req-measures-b', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-09'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','dischargeAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09-req-measures-c', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-09'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','coolStage1Cmd_on_runtime','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/* Heating does not work */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12-req-measures-a', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-12'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','zoneAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12-req-measures-b', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-12'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','dischargeAirTempSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12-req-measures-c', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-12'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','heatStage1Cmd_on_runtime','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/*Proving Fan */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-03'),'IN-PARAMETER','REQUIRED_MEASURES_AVG','','dischargeAirFanCurrentSensor','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/*Excessive HVAC Overrides - Count*/
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-05'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','hvacOverrideStatus_true','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/*LIGHTING COUNT OVERRIDE */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-06'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','lightOverrideStatus_true','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/*HVAC TIME OVERRIDE */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-07'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','hvacOverrideStatus_true_runtime','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/*HVAC Excessive usage */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-22'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','coolStage1Cmd_on_runtime,heatStage1Cmd_on_runtime','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);

/*Lighting Excessive usage */
INSERT INTO ie_emsstage_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23-req-measures', (SELECT ie_emsstage_emsrules.rule.rule_id FROM ie_emsstage_emsrules.rule WHERE ie_emsstage_emsrules.rule.rule_uid='RULE-UID-23'),'IN-PARAMETER','REQUIRED_MEASURES_AGGR','','lightCmd_on_runtime','','String','N/A',DEFAULT,'REQUIRED_MEASURES',DEFAULT,DEFAULT);



