-- --------------------------------------------------------------------------------
-- Program Name: v1_010_changeRuleName.sql
--
--      Purpose: Change ruleName
--
--
--       Inputs: None
--
--      Outputs: None
--
--      Commits: Yes
--
-- ---------------------------------------------------------------------------------
-- Modifications:
-- Date:      By:         Modified:
-- ---------------------------------------------------------------------------------
-- 05/04/2017 M.Flores   Initial version.
--
-- ---------------------------------------------------------------------------------
UPDATE emsdev_emsrules.rule SET rule_name='Supply Air Fan Failure' WHERE rule_name='Discharge Air Fan Failure';
