/* insert rule properties */
/* Zone Temperature Too High */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'IN-PARAMETER','comfortThreshold','Temperature Threshold','74','74','DOUBLE','F',DEFAULT,'Temperature Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'MIN-IN-PARAMETER','comfortThreshold.min','Minimum Temperature Threshold','60','60','DOUBLE','F',0,'Minimum Temperature Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'MAX-IN-PARAMETER','comfortThreshold.max','Maximum Temperature Threshold','80','80','DOUBLE','F',0,'Maximum Temperature Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01g', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'IN-PARAMETER','duration','Duration','60','60','DOUBLE','minutes',DEFAULT,'Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01h', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'MIN-IN-PARAMETER','duration.min','Minimum Duration','15','15','DOUBLE','minutes',0,'Minimum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01i', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'MAX-IN-PARAMETER','duration.max','Maximum Duration','240','240','DOUBLE','minutes',0,'Maximum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-01e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too High'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* Zone Temperature Too Low */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'IN-PARAMETER','comfortThreshold','Temperature Threshold','66','66','DOUBLE','F',DEFAULT,'Temperature Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'MIN-IN-PARAMETER','comfortThreshold.min','Minimum Temperature Threshold','60','60','DOUBLE','F',0,'Minimum Temperature Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'MAX-IN-PARAMETER','comfortThreshold.max','Maximum Temperature Threshold','80','80','DOUBLE','F',0,'Maximum Temperature Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02g', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'IN-PARAMETER','duration','Duration','60','60','DOUBLE','minutes',DEFAULT,'Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02h', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'MIN-IN-PARAMETER','duration.min','Minimum Duration','15','15','DOUBLE','minutes',0,'Minimum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02i', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'MAX-IN-PARAMETER','duration.max','Maximum Duration','240','240','DOUBLE','minutes',0,'Maximum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-02f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Temperature Too Low'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);

/* Air Fan Failure */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Discharge Air Fan Failure'),'IN-PARAMETER','currentThreshold','Current Threshold','0.1','0.1','DOUBLE','A',DEFAULT,'Current Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Discharge Air Fan Failure'),'MIN-IN-PARAMETER','currentThreshold.min','Minimum Current Threshold','1','1','DOUBLE','A',0,'Minimum Current Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Discharge Air Fan Failure'),'MAX-IN-PARAMETER','currentThreshold.max','Maximum Current Threshold','4','4','DOUBLE','A',0,'Maximum Current Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Discharge Air Fan Failure'),'IN-PARAMETER','severity','Severity','4','4','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Discharge Air Fan Failure'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-03f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Discharge Air Fan Failure'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);

/* Cooling not working*/
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09a',(SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'IN-PARAMETER','minITD','Delta T','18','18','DOUBLE','F',DEFAULT,'Delta T',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09b',(SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'MIN-IN-PARAMETER','minITD.min','Minimum Delta T','1','1','DOUBLE','F',0,'Minimum Delta T',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09c',(SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'MAX-IN-PARAMETER','minITD.max','Maximum Delta T','30','30','DOUBLE','F',0,'Maximum Delta T',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'IN-PARAMETER','duration','Duration','60','60','DOUBLE','minutes',DEFAULT,'Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'MIN-IN-PARAMETER','duration.min','Minimum duration','15','15','DOUBLE','minutes',0,'Minimum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'MAX-IN-PARAMETER','duration.max','Minimum duration ','240','240','DOUBLE','minutes',0,'Maximum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09g', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09h', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-09i', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Delta T Too High'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* Heating not working*/
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12a',(SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'IN-PARAMETER','minITD','Delta T','18','18','DOUBLE','F',DEFAULT,'Delta T',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12b',(SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'MIN-IN-PARAMETER','minITD.min','Minimum Delta T','1','1','DOUBLE','F',0,'Minimum Delta T',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12c',(SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'MAX-IN-PARAMETER','minITD.max','Maximum Delta T','30','30','DOUBLE','F',0,'Maximum Delta T',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'IN-PARAMETER','duration','Duration','60','60','DOUBLE','minutes',DEFAULT,'Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'MIN-IN-PARAMETER','duration.min','Minimum duration','15','15','DOUBLE','minutes',0,'Minimum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'MAX-IN-PARAMETER','duration.max','Minimum duration ','240','240','DOUBLE','minutes',0,'Maximum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12g', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12h', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-12i', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Delta T Too High'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* Zone temperature too high*/
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'IN-PARAMETER','setpointOffset','Setpoint Offset','2','2','DOUBLE','F',DEFAULT,'Setpoint Offset',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'MIN-IN-PARAMETER','setpointOffset.min','Minimum Setpoint Offset','1','1','DOUBLE','F',0,'Minimum Setpoint Offset',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'MAX-IN-PARAMETER','setpointOffset.max','Maximum Setpoint Offset','10','10','DOUBLE','F',0,'Maximum Setpoint Offset',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'IN-PARAMETER','duration','Duration','60','60','DOUBLE','minutes',DEFAULT,'Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'MIN-IN-PARAMETER','duration.min','Minimum Duration','15','15','DOUBLE','minutes',0,'Minimum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'MAX-IN-PARAMETER','duration.max','Maximum Duration','240','240','DOUBLE','minutes',0,'Maximum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20g', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20h', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-20i', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Cooling Setpoint Unreachable'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* Zone temperature too low*/
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'IN-PARAMETER','setpointOffset','Setpoint Offset','2','2','DOUBLE','F',DEFAULT,'Setpoint Offset',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'MIN-IN-PARAMETER','setpointOffset.min','Minimum Setpoint Offset','1','1','DOUBLE','F',0,'Minimum Setpoint Offset',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'MAX-IN-PARAMETER','setpointOffset.max','Maximum Setpoint Offset','10','10','DOUBLE','F',0,'Maximum Setpoint Offset',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'IN-PARAMETER','duration','Duration','60','60','DOUBLE','minutes',DEFAULT,'Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'MIN-IN-PARAMETER','duration.min','Minimum Duration','15','15','DOUBLE','minutes',0,'Minimum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'MAX-IN-PARAMETER','duration.max','Maximum Duration','240','240','DOUBLE','minutes',0,'Maximum Duration',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21g', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21h', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-21i', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Zone Heating Setpoint Unreachable'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* Short Cycle Thermostat */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-04a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Short Cycling'),'IN-PARAMETER','user_Threshold','Cycles Threshold ','6','6','DOUBLE','numeric',DEFAULT,'Cycles Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-04b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Short Cycling'),'MIN-IN-PARAMETER','user_Threshold.min','Minimum Cycles Threshold ','1','1','DOUBLE','numeric',0,'Minimum Cycles Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-04c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Short Cycling'),'MAX-IN-PARAMETER','user_Threshold.max','Maximum Cycles Threshold ','10','10','DOUBLE','numeric',0,'Maximum Cycles Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-04d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Short Cycling'),'IN-PARAMETER','severity','Severity ','2','2','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-04e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Short Cycling'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-04f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Short Cycling'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);

/*HVAC COUNT OVERRIDE */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides'),'IN-PARAMETER','user_Threshold','Threshold','10','10','DOUBLE','numeric',DEFAULT,'Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides'),'MIN-IN-PARAMETER','user_Threshold.min','Minimum Threshold','1','1','DOUBLE','numeric',0,'Minimum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides'),'MAX-IN-PARAMETER','user_Threshold.max','Maximum Threshold','30','30','DOUBLE','numeric',0,'Maximum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides'),'IN-PARAMETER','severity','Severity','3','3','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-05f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);

/*Lighting COUNT OVERRIDE */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Overrides'),'IN-PARAMETER','user_Threshold','Threshold','10','10','DOUBLE','numeric',DEFAULT,'Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Overrides'),'MIN-IN-PARAMETER','user_Threshold.min','Minimum Threshold','1','1','DOUBLE','numeric',0,'Minimum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Overrides'),'MAX-IN-PARAMETER','user_Threshold.max','Maximum Threshold','30','30','DOUBLE','numeric',0,'Maximum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Overrides'),'IN-PARAMETER','severity','Severity ','2','2','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Overrides'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-06f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Overrides'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/*HVAC Time OVERRIDE */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides Runtime'),'IN-PARAMETER','user_Threshold','Threshold','360','360','DOUBLE','minutes',DEFAULT,'Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides Runtime'),'MIN-IN-PARAMETER','user_Threshold.min','Minimum Threshold','1','1','DOUBLE','minutes',0,'Minimum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides Runtime'),'MAX-IN-PARAMETER','user_Threshold.max','Maximum Threshold','720','720','DOUBLE','minutes',0,'Maximum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides Runtime'),'IN-PARAMETER','severity','Severity ','2','2','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides Runtime'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-07f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Overrides Runtime'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* HVAC Excessive USAGE */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Usage After Hours'),'IN-PARAMETER','user_Threshold','Threshold','360','360','DOUBLE','minutes',DEFAULT,'Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Usage After Hours'),'MIN-IN-PARAMETER','user_Threshold.min','Minimum Threshold','1','1','DOUBLE','minutes',0,'Minimum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Usage After Hours'),'MAX-IN-PARAMETER','user_Threshold.max','Maximum Threshold','720','720','DOUBLE','minutes',0,'Maximum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Usage After Hours'),'IN-PARAMETER','severity','Severity ','2','2','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Usage After Hours'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-22f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive HVAC Usage After Hours'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);


/* Lighting Excessive USAGE */
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23a', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Usage After Hours'),'IN-PARAMETER','user_Threshold','Threshold ','360','360','DOUBLE','minutes',DEFAULT,'Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23b', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Usage After Hours'),'MIN-IN-PARAMETER','user_Threshold.min','Minimum Threshold','1','1','DOUBLE','minutes',0,'Minimum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23c', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Usage After Hours'),'MAX-IN-PARAMETER','user_Threshold.max','Maximum Threshold','720','720','DOUBLE','minutes',0,'Maximum Threshold',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23d', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Usage After Hours'),'IN-PARAMETER','severity','Severity ','2','2','DOUBLE','numeric',DEFAULT,'Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23e', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Usage After Hours'),'MIN-IN-PARAMETER','severity.min','Minimum Severity','1','1','DOUBLE','numeric',0,'Minimum Rule Severity',DEFAULT,DEFAULT);
INSERT INTO ie_emsqa_emsrules.rule_property (rule_property_id,rule_property_uid,rule_id,rule_property_type,name,alias,value,value_default,data_type,uom_cde,is_editable,description,update_timestamp,entry_timestamp) VALUES (DEFAULT,'RULE-PROP-UID-23f', (SELECT ie_emsqa_emsrules.rule.rule_id FROM ie_emsqa_emsrules.rule WHERE ie_emsqa_emsrules.rule.rule_name='Excessive Lighting Usage After Hours'),'MAX-IN-PARAMETER','severity.max','Maximum Severity','4','4','DOUBLE','numeric',0,'Maximum Rule Severity',DEFAULT,DEFAULT);

