INSERT INTO ie_ems_dev.events_byminute_stg (event_bucket,yyyymmdd, hhmm, resrc_type, resrc_uid, enterprise_uid, ext_props, measures_avg)
VALUES ('America/Los_Angeles','20170329','0000','ASSET', 'ASSET_2f5d9d5c-250a-35af-9e79-a6a38d8a75a5', 'enterprise_GE',
{'LT': 'HVAC_111222333444', 'LT2': 'HVAC', 'assetName': 'AHU_At_FirstFloor', 'asset_type': 'AHU', 'site_uid': 'Site_1'},
{'measures_avgcurrentSensorValue': 1, 'measures_avgdischargeAirTempSensor': 70, 'measures_avgoutsideAirTempSensor': 59, 'measures_avgrtuCoolStage_on_runtime': 100, 'measures_avgrtuHeatStage1_on_runtime': 100, 'measures_avgzoneAirTempEffectiveSp': 80, 'measures_avgzoneAirTempOccCoolingSp': 68, 'measures_avgzoneAirTempSensor': 80}
);


INSERT INTO ie_ems_dev.events_byminute_stg (event_bucket,yyyymmdd, hhmm, resrc_type, resrc_uid, enterprise_uid, ext_props, measures_avg)
VALUES ('America/Los_Angeles','20170329','0015','ASSET', 'ASSET_2f5d9d5c-250a-35af-9e79-a6a38d8a75a5', 'enterprise_GE',
{'LT': 'HVAC_111222333444', 'LT2': 'HVAC', 'assetName': 'AHU_At_FirstFloor', 'asset_type': 'AHU', 'site_uid': 'Site_1'},
{'measures_avgcurrentSensorValue': 1, 'measures_avgdischargeAirTempSensor': 70, 'measures_avgoutsideAirTempSensor': 59, 'measures_avgrtuCoolStage_on_runtime': 100, 'measures_avgrtuHeatStage1_on_runtime': 100, 'measures_avgzoneAirTempEffectiveSp': 80, 'measures_avgzoneAirTempOccCoolingSp': 68, 'measures_avgzoneAirTempSensor': 80}
);


INSERT INTO ie_ems_dev.events_byminute_stg (event_bucket,yyyymmdd, hhmm, resrc_type, resrc_uid, enterprise_uid, ext_props, measures_avg)
VALUES ('America/Los_Angeles','20170329','0030','ASSET', 'ASSET_2f5d9d5c-250a-35af-9e79-a6a38d8a75a5', 'enterprise_GE',
{'LT': 'HVAC_111222333444', 'LT2': 'HVAC', 'assetName': 'AHU_At_FirstFloor', 'asset_type': 'AHU', 'site_uid': 'Site_1'},
{'measures_avgcurrentSensorValue': 1, 'measures_avgdischargeAirTempSensor': 70, 'measures_avgoutsideAirTempSensor': 59, 'measures_avgrtuCoolStage_on_runtime': 100, 'measures_avgrtuHeatStage1_on_runtime': 100, 'measures_avgzoneAirTempEffectiveSp': 80, 'measures_avgzoneAirTempOccCoolingSp': 68, 'measures_avgzoneAirTempSensor': 80}
);


INSERT INTO ie_ems_dev.events_byminute_stg (event_bucket,yyyymmdd, hhmm, resrc_type, resrc_uid, enterprise_uid, ext_props, measures_avg)
VALUES ('America/Los_Angeles','20170329','0045','ASSET', 'ASSET_2f5d9d5c-250a-35af-9e79-a6a38d8a75a5', 'enterprise_GE',
{'LT': 'HVAC_111222333444', 'LT2': 'HVAC', 'assetName': 'AHU_At_FirstFloor', 'asset_type': 'AHU', 'site_uid': 'Site_1'},
{'measures_avgcurrentSensorValue': 1, 'measures_avgdischargeAirTempSensor': 70, 'measures_avgoutsideAirTempSensor': 59, 'measures_avgrtuCoolStage_on_runtime': 100, 'measures_avgrtuHeatStage1_on_runtime': 100, 'measures_avgzoneAirTempEffectiveSp': 80, 'measures_avgzoneAirTempOccCoolingSp': 68, 'measures_avgzoneAirTempSensor': 80}
);


INSERT INTO ie_ems_dev.events_byminute_stg (event_bucket,yyyymmdd, hhmm, resrc_type, resrc_uid, enterprise_uid, ext_props, measures_avg)
VALUES ('America/Los_Angeles','20170329','0100','ASSET', 'ASSET_2f5d9d5c-250a-35af-9e79-a6a38d8a75a5', 'enterprise_GE',
{'LT': 'HVAC_111222333444', 'LT2': 'HVAC', 'assetName': 'AHU_At_FirstFloor', 'asset_type': 'AHU', 'site_uid': 'Site_1'},
{'measures_avgcurrentSensorValue': 1, 'measures_avgdischargeAirTempSensor': 70, 'measures_avgoutsideAirTempSensor': 59, 'measures_avgrtuCoolStage_on_runtime': 100, 'measures_avgrtuHeatStage1_on_runtime': 100, 'measures_avgzoneAirTempEffectiveSp': 80, 'measures_avgzoneAirTempOccCoolingSp': 68, 'measures_avgzoneAirTempSensor': 80}
);